name: Run Pay Tests

# Controls when the workflow will run
on: [push, repository_dispatch, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test-pay:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      ganache:
        image: ghcr.io/zcaudate/infra-ganache:main
        options: >
          --entrypoint 'ganache --gasLimit 10000000000 --chain.allowUnlimitedContractSize --wallet.seed test --host 0.0.0.0'
        ports:
          - 8545:8545

    steps: 
      - name: Checkout foundation-base
        uses: actions/checkout@v3
        with:
          repository: zcaudate/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout statstrade-pay-public
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-pay-public
          path: statstrade-pay-public
          token: ${{ secrets.GH_TOKEN }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
 
      - name: Run Statspay tests
        run: docker run --rm --network host -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -w $(pwd) ghcr.io/zcaudate/foundation-ci:main bash -c 'cd statstrade-pay-public && make setup-checkouts && lein test-pay'
